### ISSUE TITLE
Support for 1.20.4?

### ISSUE THREAD

**Issue by misaka00251** [andylizi/haproxy-detector#11]
I'm using spigot 1.20.4 w/ latest dev build from [here](https://github.com/andylizi/haproxy-detector/issues/3#issuecomment-1221897495).

Here is the error log:

```
[13:23:30] [Server thread/ERROR]: Error occurred while enabling HAProxyDetector v3.1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
        at net.andylizi.haproxydetector.bukkit.BukkitMain.onEnable(BukkitMain.java:51) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4021-Spigot-864e4ac-fb97348]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4021-Spigot-864e4ac-fb97348]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:220) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4021-Spigot-864e4ac-fb97348]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4021-Spigot-864e4ac-fb97348]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4021-Spigot-864e4ac-fb97348]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 10 more
```

**Comment by misaka00251** [comment]
Oops, It seems I need to update ProtocolLib from [here](https://ci.dmulloy2.net/job/ProtocolLib/lastBuild/).
