### ISSUE TITLE
更新 ProtocolLib 5.0

### ISSUE THREAD

**Issue by From-pErfo** [andylizi/haproxy-detector#3]
可以支持 ProtocolLib 5.0 吗? 
其他插件需要新的ProtocolLib才能运行, 我无法再使用4.7版本

```
[00:02:23 INFO]: [ProtocolLib] Loading ProtocolLib v5.0.0-SNAPSHOT-b554
[00:02:24 INFO]: [HAProxyDetector] Loading HAProxyDetector v2.2
[00:02:24 INFO]: [ProtocolLib] Enabling ProtocolLib v5.0.0-SNAPSHOT-b554
[00:02:24 INFO]: [ProtocolLib] Started structure compiler thread.
[00:02:24 INFO]: [HAProxyDetector] Enabling HAProxyDetector v2.2*
[00:02:24 ERROR]: Error occurred while enabling HAProxyDetector v2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/netty/ProtocolInjector
        at net.andylizi.haproxydetector.bukkit.BukkitMain.onEnable(BukkitMain.java:34) ~[haproxy-detector-2.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.netty.ProtocolInjector
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 10 more
[00:02:24 INFO]: [HAProxyDetector] Disabling HAProxyDetector v2.2
```

**Comment by andylizi** [comment]
看了一下，ProtocolLib 5.0.0 都还没正式发布呢，十天前这个版本号才第一次出现。我实在无法想象会有插件依赖这么新的版本……你可能指的是最近发布的 4.8.0？

最终肯定是打算跟进的，但我希望至少等到 5.0.0 正式发布吧，因为我看这次有一大堆修改，尤其是我插件依赖的注入逻辑部分，可能后面还会有改变。

**Comment by From-pErfo** [comment]
似乎ProtocolLib很难发布正式版, 但只有5.0.0的开发板支持MC1.19. 是否能考虑提前一下?

**Comment by andylizi** [comment]
好吧，也是。一定要等正式版的话得不知道猴年马月了，何况这还是一个 major 版本。不过这种情况的话那就得两个版本都要想办法兼容了，头大……

最近这段时间太忙了，不过到了八月应该就有空了吧……

**Comment by andylizi** [comment]
咳咳，眼看就要八月底了，我汇报一下进度哈。

其实支持 5.0.0 的代码一周前已经写好了，我本地也简单测试了一下，应该没问题。之所以现在还没发布，是我看这不断改需求之后的代码组织的太烂了，想重构一下再发布。但现在麻烦事情一件接一件，一直没找到时间写完。

总而言之，快照版我先发出来，急得话可以先用着。至于正式版嘛……之后再说（逃

[haproxy-detector-3.1.0-SNAPSHOT.jar.zip](https://github.com/andylizi/haproxy-detector/files/9391708/haproxy-detector-3.1.0-SNAPSHOT.jar.zip)
（Github 不让上传 jar，记得解压 zip）

**Comment by NovaPixell** [comment]
> 咳咳，眼看就要八月底了，我汇报一下进度哈。
> 
> 其实支持 5.0.0 的代码一周前已经写好了，我本地也简单测试了一下，应该没问题。之所以现在还没发布，是我看这不断改需求之后的代码组织的太烂了，想重构一下再发布。但现在麻烦事情一件接一件，一直没找到时间写完。
> 
> 总而言之，快照版我先发出来，急得话可以先用着。至于正式版嘛……之后再说（逃
> 
> [haproxy-detector-3.1.0-SNAPSHOT.jar.zip](https://github.com/andylizi/haproxy-detector/files/9391708/haproxy-detector-3.1.0-SNAPSHOT.jar.zip) （Github 不让上传 jar，记得解压 zip）

Nice!

**Comment by chaojixiaomengxin** [comment]
现在ProtocolLib已经正式更新到5.0.0了吧

**Comment by fmfmqs** [comment]
已经在用着ProtocolLib-v5.1.1了orz
